#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          oled
# Required-Start:    $remote_fs $local_fs
# Required-Stop:     $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Oled cleaner
# Description:       Clears oled during shutdown
### END INIT INFO


case $1 in
 start)
  ;;
 stop)
    oled r
    sudo oled s
  ;;
 restart)
  ;;
 status)
  ;;
 reload)
  ;;
 *)
  # For invalid arguments, print the usage message.
  echo "Usage: $0 {start|stop|restart|reload|status}"
  exit 2
  ;;
esac
